package com.qmy.qmybdata.entity;

public class AreaBuildingColumnInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.ranch
     *
     * @mbg.generated
     */
    private String ranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.building
     *
     * @mbg.generated
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.nsheeps
     *
     * @mbg.generated
     */
    private String nsheeps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.bak1
     *
     * @mbg.generated
     */
    private String bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.bak2
     *
     * @mbg.generated
     */
    private String bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.bak3
     *
     * @mbg.generated
     */
    private String bak3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columninfo.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.id
     *
     * @return the value of columninfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.id
     *
     * @param id the value for columninfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.ranch
     *
     * @return the value of columninfo.ranch
     *
     * @mbg.generated
     */
    public String getRanch() {
        return ranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.ranch
     *
     * @param ranch the value for columninfo.ranch
     *
     * @mbg.generated
     */
    public void setRanch(String ranch) {
        this.ranch = ranch == null ? null : ranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.region
     *
     * @return the value of columninfo.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.region
     *
     * @param region the value for columninfo.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.building
     *
     * @return the value of columninfo.building
     *
     * @mbg.generated
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.building
     *
     * @param building the value for columninfo.building
     *
     * @mbg.generated
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.number
     *
     * @return the value of columninfo.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.number
     *
     * @param number the value for columninfo.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.name
     *
     * @return the value of columninfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.name
     *
     * @param name the value for columninfo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.nsheeps
     *
     * @return the value of columninfo.nsheeps
     *
     * @mbg.generated
     */
    public String getNsheeps() {
        return nsheeps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.nsheeps
     *
     * @param nsheeps the value for columninfo.nsheeps
     *
     * @mbg.generated
     */
    public void setNsheeps(String nsheeps) {
        this.nsheeps = nsheeps == null ? null : nsheeps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.bak1
     *
     * @return the value of columninfo.bak1
     *
     * @mbg.generated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.bak1
     *
     * @param bak1 the value for columninfo.bak1
     *
     * @mbg.generated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.bak2
     *
     * @return the value of columninfo.bak2
     *
     * @mbg.generated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.bak2
     *
     * @param bak2 the value for columninfo.bak2
     *
     * @mbg.generated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.bak3
     *
     * @return the value of columninfo.bak3
     *
     * @mbg.generated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.bak3
     *
     * @param bak3 the value for columninfo.bak3
     *
     * @mbg.generated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columninfo.remarks
     *
     * @return the value of columninfo.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columninfo.remarks
     *
     * @param remarks the value for columninfo.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}