package com.qmy.qmybdata.entity;

public class PastureInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.ranch
     *
     * @mbg.generated
     */
    private String ranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breed_famer.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.id
     *
     * @return the value of breed_famer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.id
     *
     * @param id the value for breed_famer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.ranch
     *
     * @return the value of breed_famer.ranch
     *
     * @mbg.generated
     */
    public String getRanch() {
        return ranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.ranch
     *
     * @param ranch the value for breed_famer.ranch
     *
     * @mbg.generated
     */
    public void setRanch(String ranch) {
        this.ranch = ranch == null ? null : ranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.leader
     *
     * @return the value of breed_famer.leader
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.leader
     *
     * @param leader the value for breed_famer.leader
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.phone
     *
     * @return the value of breed_famer.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.phone
     *
     * @param phone the value for breed_famer.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.amount
     *
     * @return the value of breed_famer.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.amount
     *
     * @param amount the value for breed_famer.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breed_famer.number
     *
     * @return the value of breed_famer.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breed_famer.number
     *
     * @param number the value for breed_famer.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}