package com.qmy.qmybdata.entity;

import lombok.Data;

import java.util.Date;

@Data
public class SheepInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.recorddate
     *
     * @mbg.generated
     */
    private Date recorddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.ranch
     *
     * @mbg.generated
     */
    private String ranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.eartagid
     *
     * @mbg.generated
     */
    private String eartagid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.buildingnum
     *
     * @mbg.generated
     */
    private String buildingnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.columnnum
     *
     * @mbg.generated
     */
    private String columnnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.species
     *
     * @mbg.generated
     */
    private String species;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.stage
     *
     * @mbg.generated
     */
    private String stage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.colour
     *
     * @mbg.generated
     */
    private String colour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.video
     *
     * @mbg.generated
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.startdate
     *
     * @mbg.generated
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.enddate
     *
     * @mbg.generated
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.bak1
     *
     * @mbg.generated
     */
    private String bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.bak2
     *
     * @mbg.generated
     */
    private String bak2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.bak3
     *
     * @mbg.generated
     */
    private String bak3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstrecord.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;
    private String farmloc;
    private String bornloc;
    private String borntime;
    private String bornweight;
    private String motherid;
    private String fatherid;
}