package com.qmy.qmybdata.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class TokenInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.appKey
     *
     * @mbg.generated
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.appSecret
     *
     * @mbg.generated
     */
    private String appSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.expireTime
     *
     * @mbg.generated
     */
    private String expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.accessToken
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.name
     *
     * @mbg.generated
     */
    private String name;
}