package com.qmy.qmybdata.entity;

import java.util.Date;

public class TradeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.chufadi
     *
     * @mbg.generated
     */
    private String chufadi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.arriving
     *
     * @mbg.generated
     */
    private String arriving;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.goods
     *
     * @mbg.generated
     */
    private String goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.id
     *
     * @return the value of transport.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.id
     *
     * @param id the value for transport.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.chufadi
     *
     * @return the value of transport.chufadi
     *
     * @mbg.generated
     */
    public String getChufadi() {
        return chufadi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.chufadi
     *
     * @param chufadi the value for transport.chufadi
     *
     * @mbg.generated
     */
    public void setChufadi(String chufadi) {
        this.chufadi = chufadi == null ? null : chufadi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.arriving
     *
     * @return the value of transport.arriving
     *
     * @mbg.generated
     */
    public String getArriving() {
        return arriving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.arriving
     *
     * @param arriving the value for transport.arriving
     *
     * @mbg.generated
     */
    public void setArriving(String arriving) {
        this.arriving = arriving == null ? null : arriving.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.time
     *
     * @return the value of transport.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.time
     *
     * @param time the value for transport.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.goods
     *
     * @return the value of transport.goods
     *
     * @mbg.generated
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.goods
     *
     * @param goods the value for transport.goods
     *
     * @mbg.generated
     */
    public void setGoods(String goods) {
        this.goods = goods == null ? null : goods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.num
     *
     * @return the value of transport.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.num
     *
     * @param num the value for transport.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}