package com.qmy.qmybdata.entity;

import lombok.Data;

@Data
public class VideoInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.house
     *
     * @mbg.generated
     */
    private String house;

//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.videoAddress
//     *
//     * @mbg.generated
//     */
//    private String videoAddress;
//
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.deviceSerial
     *
     * @mbg.generated
     */
    private String deviceSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.channelNo
     *
     * @mbg.generated
     */
    private String channelNo;

//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.flvAddress
//     *
//     * @mbg.generated
//     */
//    private String flvAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.hdAddress
//     *
//     * @mbg.generated
//     */
//    private String hdAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.hdFlvAddress
//     *
//     * @mbg.generated
//     */
//    private String hdflvAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.liveAddress
//     *
//     * @mbg.generated
//     */
//    private String liveAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.rtmp
//     *
//     * @mbg.generated
//     */
//    private String rtmp;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column t_video.rtmpHd
//     *
//     * @mbg.generated
//     */
//    private String rtmpHd;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.status
     *
     * @mbg.generated
     */
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.status
     *
     * @mbg.generated
     */
    private String status;

}
