package com.qmy.qmybdata.mapper;

import com.qmy.qmybdata.entity.AreaBuildingColumnInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AreaBuildingColumnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    int insert(AreaBuildingColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    int insertSelective(AreaBuildingColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    AreaBuildingColumnInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AreaBuildingColumnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columninfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AreaBuildingColumnInfo record);

    /**
     * 查询所有的区域
     * @return
     */
    List<String> listAllregion();
    List<String> listAllregion1();

    /**
     * 查询所有的圈舍
     * @return
     */
    List<String> listAllbuilding();
    List<String> listAllbuilding1();
}
