package com.qmy.qmybdata.mapper;

import com.qmy.qmybdata.entity.SheepInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.HashMap;
import java.util.List;

@Mapper
public interface SheepInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    int insert(SheepInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    int insertSelective(SheepInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    SheepInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SheepInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SheepInfo record);

    /**
     * 根据特定条件查询羊只信息
     * @param sheepInfo
     * @return
     */
    List<SheepInfo> selectSheepByCondition(SheepInfo sheepInfo);
    /**
     * 查询所有的品种
     * @return
     */
    List<String> listAllspecies();

    /**
     * 查询所有的类型
     * @return
     */
    List<String> listAlltype();

    /**
     * 按照条件查询耳标号
     * @param sheepInfo
     * @return
     */
    List<String> listEarnumByCondition(SheepInfo sheepInfo);
}