package com.qmy.qmybdata.mapper;

import com.qmy.qmybdata.entity.TokenInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TokenInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    int insert(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    int insertSelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    TokenInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TokenInfo record);

    /**
     * 根据条件查询token信息
     * @param tokenInfo
     * @return
     */
    List<TokenInfo> selectByCondition(TokenInfo tokenInfo);

    /**
     * 根据条件更新信息
     * @param tokenInfo
     */
    void updateByCondition(TokenInfo tokenInfo);

    /**
     * 根据用户名选择token信息
     * @param name
     * @return
     */
    TokenInfo selectByName(String name);
}