package com.qmy.qmybdata.mapper;

import com.qmy.qmybdata.entity.VideoInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VideoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    int insert(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    int insertSelective(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    VideoInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoInfo record);
    /**
     * 根据条件查询视频信息
     */
    List<VideoInfo> selectByCondition(VideoInfo videoInfo);
}